### ISSUE TITLE
Not able to track dom manipulations as shown on demo

### ISSUE THREAD

**Issue by coderkd10** [pilagod/js-tracker#1]
First of all, awesome project, just ❤️demo. It will be super useful to me during my day job.

I tried to run the scenario shown in demo (i.e. visited https://pilagod.github.io/js-tracker/example/ and clicked on the button). But I could not see the button click events as shown in the demo, and I am getting "Have no matched records yet :)" (I have attached screenshot below)

<img width="1680" alt="screen shot 2018-02-27 at 11 01 44 pm" src="https://user-images.githubusercontent.com/11814794/36744202-34c2ed80-1c12-11e8-83cc-dd585618ffa6.png">

I tried to look for the source of the error and opened the dev console for the extension and got the followings error, which I think might be useful for debugging - 

```
inspector.js:7810 Extension server error: 

stack trace - 

makeStatus @ inspector.js:7810
evaluate @ inspector.js:7803
_onEvaluateOnInspectedPage @ inspector.js:7713
_onmessage @ inspector.js:7775


inspector.js:4882 Cannot find context with specified id

stack trace -

_evaluateGlobal @ inspector.js:4882
async function (async)
_evaluateGlobal @ inspector.js:4881
evaluate @ inspector.js:4879
evaluate @ inspector.js:7807
_onEvaluateOnInspectedPage @ inspector.js:7713
_onmessage @ inspector.js:7775


inspector.js:7810 Extension server error: Inspector protocol error: Cannot find context with specified id

stack trace -

makeStatus @ inspector.js:7810
callback @ inspector.js:7710
onEvaluate @ inspector.js:7807
Promise.then (async)
evaluate @ inspector.js:7807
_onEvaluateOnInspectedPage @ inspector.js:7713
_onmessage @ inspector.js:7775

```

I'm running Chrome v64.0.3282.167 (64bit) on macOS Sierra v10.12.4

**Comment by pilagod** [comment]
I'm so glad that you like it 😃

It seems like the extension background service doesn't connect properly to the developer tool. 

Let me try to figure out what is going on 😢

**Comment by pilagod** [comment]
Is the yellow warning message in your console something like

 ```
The JavaScript context chrome-extension://pdkjocgjcabjddpnefbdkdeadfancbgh was not found in the frame https://pilagod.github.io/js-tracker/example/
```

**Comment by coderkd10** [comment]
yes. i'm attaching a screenshot of the console for your reference.
<img width="1189" alt="screen shot 2018-02-27 at 11 44 33 pm" src="https://user-images.githubusercontent.com/11814794/36746401-40e85996-1c18-11e8-9c61-4f3827ea1c47.png">

**Comment by pilagod** [comment]
I think you might interact with the wrong page, when you click JavaScript Tracker, it will open another new page, and tracker is enabled only in that new page.

Try to click tracker again, and notice if there is a new tab opened

**Comment by coderkd10** [comment]
Clicking on `JS-Tracker` in dev tools does not open a new page / tab for me

**Comment by coderkd10** [comment]
Ok... I viewed the demo again. And yes after opening any page, clicking on the extensions icon does open a new tab with the same page. But even in the new page I don't see the events getting triggered.

**Comment by pilagod** [comment]
Sorry for my unclear instructions 😢

That's weird 😔 Are there any errors in the new page ?

**Comment by coderkd10** [comment]
In the new page also I don't see any events. I have create a short screencast for the same - https://vimeo.com/257760542

**Comment by coderkd10** [comment]
Watched the demo really carefully again.. I just figured it out now. In the new page when I open the dev tools, I have to right click exactly on the button to open the dev tools, and then I can see the events shown in the demo. Opening dev tools via keyboard shortcut / clicking anywhere else in the page to open the devtools does not seem to trigger logging of events (as was happening to me before).

**Comment by pilagod** [comment]
Yes, you are right.

The key point here is to "select (left click)" the element you want to peek in the Elements panel, JavaScript Tracker only show information about the element you selected in Elements panel in sidebar, it is indifferent to how you open the devtool.

I should do more steps in the demo 😢

**Comment by pilagod** [comment]
Here is a more detailed usage demo video：https://goo.gl/TNHW1V

You can arbitrarily change the selected element in Elements panel, you can see the sidebar displays different things when element selection is changed. Hope this video give you more clear information

**Comment by pilagod** [comment]
Thanks you for your question 😃 I am going to close this issue, welcome to comment on this again for unclear parts and open new issue if there are any other problems 🙂️
